language: python
python:
-  3.7
install:
  - sudo apt-get install build-essential python3-dev python3-pip python3-setuptools python3-wheel python3-cffi libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
  - pip install mkdocs
  - pip install mkdocs-material
  - pip install mkdocs-awesome-pages-plugin
  - pip install -e git+https://github.com/FF1204/mkpdfs-mkdocs-plugin.git#egg=mkpdfs-mkdocs-plugin
  - pip3 install mkdocs-add-number-plugin
  - pip install mkdocs-render-otherfile-plugin
script:
  - mkdocs build --clean
after_success:  |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd site
    git init
    git add .
    git -c user.name=$GITHUB_NAME -c user.email=$GITHUB_EMAIL commit -m "Auto Deployment"
    git push -f -q https://$GITHUB_NAME:$GITHUB_API_KEY@github.com/FF1204/leetcode.git master:gh-pages
    cd "$TRAVIS_BUILD_DIR"
  fi